defaults:
    - scope:
        path: ""
        source: "./docs"
        values:
        layout: "default"

exclude:
    - Makefile
    - run.sh
    - gitmodules/
    - "*.config.js"
    - "package*.json"
    - "assets"
    - "node_modules"
